import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Navbar from "../../components/navbar/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Aplikace pro dosažení cíle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Přidání odkazu na manifest */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#fff" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-cover bg-center min-h-screen bg-mobile lg:bg-desktop`}
      >
        <nav className=" md:pb-20">
          <Navbar />
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
